set nu
set bg=dark

"map the 'v' keystroke to mean 'save file unconditionally', very useful when
"my files become readonly frequently
map v :w!

"doesn't work:( Suggested on stackoverflow
map <F3> :%!xxd<CR>
