"Note on some systems vi is used instead of vim, so this file is ignored.

set nu
set bg=dark

"map the 'v' keystroke to mean 'save file unconditionally', very useful when
"my files become readonly frequently
map v :w!

"doesn't work:( Suggested on stackoverflow
map <F3> :%!xxd<CR>

" needed to make vim remember last edit location
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
